#!/bin/bash
set -euxo pipefail

echo "Running track setup script on host docker-vm"

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]

do
    sleep 1
done

# install the New Relic CLI
sudo wget https://github.com/newrelic/newrelic-cli/releases/download/v0.64.2/newrelic-cli_0.64.2_Linux_x86_64.deb
sudo dpkg -i ./newrelic-cli_0.64.2_Linux_x86_64.deb 

# make the working directories
sudo mkdir -p /var/tmp/track/config
sudo mkdir -p /var/tmp/track/apps
# Create the environment file for the user
cat <<EOF >> /var/tmp/track/config/env.sh
export NEW_RELIC_LICENSE_KEY=<your_license_key>
export NEW_RELIC_API_KEY=<your_api_key>
EOF

# Set the env files in every terminal session
cat <<EOF >> /root/.bashrc

source /var/tmp/track/config/env.sh
EOF

#Set up git repo
mkdir labsrc
cd labsrc
git init
git remote add -f origin https://github.com/newrelic-experimental/upgrading-apm-agents-lab.git

git config core.sparseCheckout true

echo "apps/" >> .git/info/sparse-checkout

git pull origin main

sudo chmod 755 apps/simple-example/*.sh
sudo chmod 755 apps/multi-service/*.sh

