version: "3.9"
services:
  
  web:
    build: ./hello-new-relic
    ports:
      - "8001:3000"
    environment:
      # Add environment variables here
      NEW_RELIC_APP_NAME: "Hello New Relic"
  
  load-generator:
    image: locustio/locust
    volumes:
      - ./loadgen:/mnt/locust
    command: --locustfile /mnt/locust/locustfile.py --host http://web:3000 --users 3 --headless --only-summary
