#!/bin/bash
set -euxo pipefail

if grep '=<.*>' /var/tmp/track/config/env.sh; then
    fail-message "It looks like you haven't edited your environment variables. (did you save the file?)"
    exit 1
fi